// <auto-generated />
namespace AcunMedyaHospitalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mşg0602252043patientcomments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mşg0602252043patientcomments));
        
        string IMigrationMetadata.Id
        {
            get { return "202502062235578_mşg0602252043patientcomments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
